language: jruby
rvm:
  - 1.7.16.1
  script:
#    - bundle exec rake db:migrate RAILS_ENV=test
    - bundle exec rspec -fd
#  before_script:
#    - cp config/database.travis.yml config/database.yml
#    - cp config/shards.travis.yml config/shards.yml
#    - cp config/secrets.travis.yml config/secrets.yml
  #branches:
  #  only:
  #    - master